
import React from 'react';
import { Product } from './types';

// This base64 string is used for embedding the DejaVu Sans font into generated PDFs.
export const DEJAVU_SANS_BASE64 = 'AAEAAAARAQAABAAQR0RFRgB5AAD/LAAAAAxPUy8y+3xJ4gAAAVgAAABgY21hcABAAGUAAAG4AAABomaGVhZBo/S4sAAAJIAAAANmhoZWEH/wPeAAACeAAAACRobXR4DAAAAAAAApAAAAA4bWF4cAAEAAEAAAMwAAAAIG5hbWU9w4CIAAAFIAAAE3Bvc3QAAwAAAAAEhAAAAAkAAQAAAAEAAEnEUl9fDzz1AAsEAAAAAAD/txoOAAAAAP+3Gg4AAP/3CVsDyQADAAEAAAAAAAAAAAAAAAAAAAABAAEAAAAJABgABAADAAAAAgABABQAAAADAAMAAQAEABoAGgABAAAAAQYABAEDAAYABgAEAAAAAQYABwEDAAYACAAWAAAAAQYAIQADAAEAAAAAAVSAAAADAAEAAAAAAXMAAAADAAEAAAAAAWwAAAADAAEAAAAAAWYAAAADAAEAAAAAAWQAAAADAAEAAAAAAWEAAAADAAEAAAAAAWAAAAADAAEAAAAAAUgAAAADAAEAAAAAAVwAAAADAAEAAAAAAU4AAAADAAEAAAAAAUgAAAADAAEAAAAAAUYAAAADAAEAAAAAAUEAAAADAAEAAAAAAUUAAAADAAEAAAAAAUIAAAADAAEAAAAAAV8AAAADAAEAAAAAAVwAAAADAAEAAAAAAVQAAAADAAEAAAAAAVMAAAADAAEAAAAAAUsAAAADAAEAAAAAAVQAAAADAAEAAAAAAUwAAAADAAEAAAAAAVAAAAADAAEAAAAAAVgAAAADAAEAAAAAAVcAAAADAAEAAAAAAVgAAAADAAEAAAAAAVQAAAADAAEAAAAAAVgAAAADAAEAAAAAAVAAAAADAAEAAAAAAWEAAAADAAEAAAAAAVkAAAADAAEAAAAAAVYAAAADAAEAAAAAAVkAAAADAAEAAAAAAWEAAAADAAEAAAAAAVMAAAADAAEAAAAAAVgAAAADAAEAAAAAAVAAAAADAAEAAAAAAVgAAAADAAEAAAAAAVoAAAADAAEAAAAAAWEAAAADAAEAAAAAAVAAAAADAAEAAAAAAVwAAAADAAEAAAAAAVYAAAADAAEAAAAAAWAAAAADAAEAAAAAAVQAAAADAAEAAAAAAVUAAAADAAEAAAAAAWEAAAADAAEAAAAAAWAAAAADAAEAAAAAAWUAAAADAAEAAAAAAXQAAAADAAEAAAAAAVgAAAADAAEAAAAAAVcAAAADAAEAAAAAAVAAAAADAAEAAAAAAVMAAAADAAEAAAAAAVQAAAADAAEAAAAAAVYAAAADAAEAAAAAAVcAAAADAAEAAAAAAVkAAAADAAEAAAAAAWUAAAADAAEAAAAAAVkAAAADAAEAAAAAAWAAAAADAAEAAAAAAVsAAAADAAEAAAAAAWEAAAADAAEAAAAAAWEAAAADAAEAAAAAVAAAAADAAEAAAAAAWAAAAADAAEAAAAAAVsAAAADAAEAAAAAAXMAAAADAAEAAAAAAXAAAAADAAEAAAAAAWsAAAADAAEAAAAAAWEAAAADAAEAAAAAAWAAAAADAAEAAAAAAXIAAAADAAEAAAAAAVcAAAADAAEAAAAAAXQAAAADAAEAAAAAAXMAAAADAAEAAAAAAWAAAAADAAEAAAAAAXMAAAADAAEAAAAAAWcAAAADAAEAAAAAAWEAAAADAAEAAAAAAWsAAAADAAEAAAAAAXAAAAADAAEAAAAAAXMAAAADAAEAAAAAAXMAAAADAAEAAAAAAXcAAAADAAEAAAAAAXQAAAADAAEAAAAAAXQAAAADAAEAAAAAAXcAAAADAAEAAAAAAWAAAAADAAEAAAAAAWEAAAADAAEAAAAAAXMAAAADAAEAAAAAAXAAAAADAAEAAAAAAWsAAAADAAEAAAAAAWYAAAADAAEAAAAAAWAAAAADAAEAAAAAAWsAAAADAAEAAAAAAWUAAAADAAEAAAAAAXQAAAADAAEAAAAAAXsAAAADAAEAAAAAAWsAAAADAAEAAAAAAWYAAAADAAEAAAAAAWUAAAADAAEAAAAAAWsAAAADAAEAAAAAAXAAAAADAAEAAAAAAWAAAAADAAEAAAAAAWsAAAADAAEAAAAAAXAAAAADAAEAAAAAAWAAAAADAAEAAAAAAWMAAAADAAEAAAAAAWYAAAADAAEAAAAAAWEAAAADAAEAAAAAAWcAAAADAAEAAAAAAWYAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXQAAAADAAEAAAAAVoAAAADAAEAAAAAAV4AAAADAAEAAAAAAXcAAAADAAEAAAAAAXsAAAADAAEAAAAAAWIAAAADAAEAAAAAAWsAAAADAAEAAAAAAWMAAAADAAEAAAAAAXQAAAADAAEAAAAAAWIAAAADAAEAAAAAAXQAAAADAAEAAAAAAXQAAAADAAEAAAAAAWUAAAADAAEAAAAAAWMAAAADAAEAAAAAAWcAAAADAAEAAAAAAWEAAAADAAEAAAAAAXUAAAADAAEAAAAAAXQAAAADAAEAAAAAAWsAAAADAAEAAAAAAXAAAAADAAEAAAAAAWsAAAADAAEAAAAAAWYAAAADAAEAAAAAAWMAAAADAAEAAAAAAXUAAAADAAEAAAAAAXQAAAADAAEAAAAAAWsAAAADAAEAAAAAAXsAAAADAAEAAAAAAWIAAAADAAEAAAAAAWYAAAADAAEAAAAAAXcAAAADAAEAAAAAAXsAAAADAAEAAAAAAWMAAAADAAEAAAAAAWsAAAADAAEAAAAAAWMAAAADAAEAAAAAAWAAAAADAAEAAAAAAXsAAAADAAEAAAAAAWEAAAADAAEAAAAAAWcAAAADAAEAAAAAAXcAAAADAAEAAAAAAWIAAAADAAEAAAAAAXQAAAADAAEAAAAAAXUAAAADAAEAAAAAAWMAAAADAAEAAAAAAXcAAAADAAEAAAAAAXQAAAADAAEAAAAAAWEAAAADAAEAAAAAAXcAAAADAAEAAAAAAXQAAAADAAEAAAAAAWMAAAADAAEAAAAAAWMAAAADAAEAAAAAAXUAAAADAAEAAAAAAWEAAAADAAEAAAAAAXUAAAADAAEAAAAAAWYAAAADAAEAAAAAAXcAAAADAAEAAAAAAXMAAAADAAEAAAAAAWEAAAADAAEAAAAAAWYAAAADAAEAAAAAAWMAAAADAAEAAAAAAWMAAAADAAEAAAAAAXsAAAADAAEAAAAAAXQAAAADAAEAAAAAAWcAAAADAAEAAAAAAWsAAAADAAEAAAAAAWYAAAADAAEAAAAAAXcAAAADAAEAAAAAAXsAAAADAAEAAAAAAWYAAAADAAEAAAAAAXQAAAADAAEAAAAAAWMAAAADAAEAAAAAAWMAAAADAAEAAAAAAWAAAAADAAEAAAAAAXsAAAADAAEAAAAAAWcAAAADAAEAAAAAAWMAAAADAAEAAAAAAWEAAAADAAEAAAAAAXsAAAADAAEAAAAAAWYAAAADAAEAAAAAAWMAAAADAAEAAAAAAWIAAAADAAEAAAAAAXcAAAADAAEAAAAAAXcAAAADAAEAAAAAAXsAAAADAAEAAAAAAWMAAAADAAEAAAAAAWAAAAADAAEAAAAAAXsAAAADAAEAAAAAAWMAAAADAAEAAAAAAXsAAAADAAEAAAAAAXcAAAADAAEAAAAAAXsAAAADAAEAAAAAAXsAAAADAAEAAAAAAXQAAAADAAEAAAAAAXQAAAADAAEAAAAAAXQAAAADAAEAAAAAAXQAAAADAAEAAAAAAXUAAAADAAEAAAAAAWMAAAADAAEAAAAAAXsAAAADAAEAAAAAAXUAAAADAAEAAAAAAWEAAAADAAEAAAAAAXQAAAADAAEAAAAAAWsAAAADAAEAAAAAAXUAAAADAAEAAAAAAWMAAAADAAEAAAAAAWIAAAADAAEAAAAAAXUAAAADAAEAAAAAAWMAAAADAAEAAAAAAXsAAAADAAEAAAAAAWEAAAADAAEAAAAAAXQAAAADAAEAAAAAAWMAAAADAAEAAAAAAWIAAAADAAEAAAAAAWMAAAADAAEAAAAAAWsAAAADAAEAAAAAAWMAAAADAAEAAAAAAWEAAAADAAEAAAAAAWsAAAADAAEAAAAAAWMAAAADAAEAAAAAAWMAAAADAAEAAAAAAWEAAAADAAEAAAAAAXsAAAADAAEAAAAAAXUAAAADAAEAAAAAAXcAAAADAAEAAAAAAWsAAAADAAEAAAAAAXQAAAADAAEAAAAAAXcAAAADAAEAAAAAAWEAAAADAAEAAAAAAXcAAAADAAEAAAAAAXUAAAADAAEAAAAAAWsAAAADAAEAAAAAAWEAAAADAAEAAAAAAXcAAAADAAEAAAAAAWsAAAADAAEAAAAAAWMAAAADAAEAAAAAAXQAAAADAAEAAAAAAWEAAAADAAEAAAAAAXcAAAADAAEAAAAAAXQAAAADAAEAAAAAAWEAAAADAAEAAAAAAXQAAAADAAEAAAAAAXQAAAADAAEAAAAAAXsAAAADAAEAAAAAAXQAAAADAAEAAAAAAXQAAAADAAEAAAAAAWEAAAADAAEAAAAAAWEAAAADAAEAAAAAAXQAAAADAAEAAAAAAXQAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAWcAAAADAAEAAAAAAXcAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXQAAAADAAEAAAAAAXQAAAADAAEAAAAAAXMAAAADAAEAAAAAAXcAAAADAAEAAAAAAXMAAAADAAEAAAAAAXUAAAADAAEAAAAAAWMAAAADAAEAAAAAAWEAAAADAAEAAAAAAXcAAAADAAEAAAAAAXcAAAADAAEAAAAAAWEAAAADAAEAAAAAAXcAAAADAAEAAAAAAXUAAAADAAEAAAAAAXcAAAADAAEAAAAAAXcAAAADAAEAAAAAAWsAAAADAAEAAAAAAXcAAAADAAEAAAAAAXMAAAADAAEAAAAAAWsAAAADAAEAAAAAAXcAAAADAAEAAAAAAXQAAAADAAEAAAAAAXsAAAADAAEAAAAAAWsAAAADAAEAAAAAAXsAAAADAAEAAAAAAXQAAAADAAEAAAAAAXUAAAADAAEAAAAAAXsAAAADAAEAAAAAAXQAAAADAAEAAAAAAXcAAAADAAEAAAAAAXMAAAADAAEAAAAAAXsAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXcAAAADAAEAAAAAAXsAAAADAAEAAAAAAXQAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXQAAAADAAEAAAAAAXMAAAADAAEAAAAAAXcAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXcAAAADAAEAAAAAAXQAAAADAAEAAAAAAXMAAAADAAEAAAAAAXsAAAADAAEAAAAAAXUAAAADAAEAAAAAAXQAAAADAAEAAAAAAXsAAAADAAEAAAAAAXsAAAADAAEAAAAAAXsAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXsAAAADAAEAAAAAAXUAAAADAAEAAAAAAXsAAAADAAEAAAAAAXQAAAADAAEAAAAAAXUAAAADAAEAAAAAAXsAAAADAAEAAAAAAXUAAAADAAEAAAAAAXAAAAADAAEAAAAAAXUAAAADAAEAAAAAAXQAAAADAAEAAAAAAXcAAAADAAEAAAAAAXQAAAADAAEAAAAAAXQAAAADAAEAAAAAAXUAAAADAAEAAAAAAXMAAAADAAEAAAAAAXcAAAADAAEAAAAAAXQAAAADAAEAAAAAAXsAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXQAAAADAAEAAAAAAXQAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXQAAAADAAEAAAAAAXcAAAADAAEAAAAAAXUAAAADAAEAAAAAAXcAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXsAAAADAAEAAAAAAXcAAAADAAEAAAAAAXcAAAADAAEAAAAAAXsAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXQAAAADAAEAAAAAAXcAAAADAAEAAAAAAXsAAAADAAEAAAAAAXQAAAADAAEAAAAAAXUAAAADAAEAAAAAAXQAAAADAAEAAAAAAXQAAAADAAEAAAAAAXcAAAADAAEAAAAAAXUAAAADAAEAAAAAAXcAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXQAAAADAAEAAAAAAXQAAAADAAEAAAAAAXcAAAADAAEAAAAAAXUAAAADAAEAAAAAAXcAAAADAAEAAAAAAXcAAAADAAEAAAAAAXcAAAADAAEAAAAAAXcAAAADAAEAAAAAAXUAAAADAAEAAAAAAXcAAAADAAEAAAAAAXcAAAADAAEAAAAAAXUAAAADAAEAAAAAAXcAAAADAAEAAAAAAXcAAAADAAEAAAAAAXcAAAADAAEAAAAAAXcAAAADAAEAAAAAAXcAAAADAAEAAAAAAXcAAAADAAEAAAAAAXcAAAADAAEAAAAAAXcAAAADAAEAAAAAAXUAAAADAAEAAAAAAXcAAAADAAEAAAAAAXUAAAADAAEAAAAAAXcAAAADAAEAAAAAAXUAAAADAAEAAAAAAXcAAAADAAEAAAAAAXcAAAADAAEAAAAAAXUAAAADAAEAAAAAAXcAAAADAAEAAAAAAXcAAAADAAEAAAAAAXcAAAADAAEAAAAAAXUAAAADAAEAAAAAAXcAAAADAAEAAAAAAXUAAAADAAEAAAAAAXcAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAXUAAAADAAEAAAAAAv/wAIAAAAAAIAAQACgANAA4AEwAXABsAIAAkACgALAAxADUANwA9AD8AQwBHAEoATABPAFEAUwBWAFkAWwBfAGEAZABnAGoAbABvAHEAdQB4AHoAfQCBAIMAhQCGALAAsgC0ALYAuQC7AL8AxADHAMwAzwDRAM0AzwDVANUA1wDZANsA3ADdAN4A3wDhAOIA4wDkAOYA6ADpAOwA7gDvAPIA9AD2APgA+wD9AP8BAAEEAQgBCwEOARIBFwEZAR0BIQEkAScBKgEtATABMwE1AUIBzAHiAf4CNAJJAkwCUAJXAlgCWgJdAmACZwJwAncCegJ/AoYCiAKLAnYAAAAABQADAPAAAgAIAAAAAAACAAAAAAAAAAAAAAAAAwAAAPAAAgAIAPAAAwAAAAIABgAIAAIAAAAAAAMAAAAAAAD/8AAA';

// Other constants defined based on usage in the app
export const NAV_LINKS = [
    { name: 'Produkty', path: '/produkty' },
    { name: 'Jak to funguje?', path: '/jak-to-funguje' },
    { name: 'Kontakt', path: '/kontakt' },
];

export const FOOTER_INFO_LINKS = [
    { name: 'Doprava a platba', path: '/doprava' },
];

export const FOOTER_LEGAL_LINKS = [
    { name: 'Obchodní podmínky', path: '/obchodni-podminky' },
    { name: 'Ochrana osobních údajů', path: '/ochrana-udaju' },
];

export const HOW_IT_WORKS_STEPS = [
    {
        icon: <svg xmlns="http://www.w3.org/2000/svg" className="h-10 w-10" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}><path strokeLinecap="round" strokeLinejoin="round" d="M4 5a1 1 0 011-1h14a1 1 0 011 1v2a1 1 0 01-1 1H5a1 1 0 01-1-1V5zM4 13a1 1 0 011-1h6a1 1 0 011 1v6a1 1 0 01-1 1H5a1 1 0 01-1-1v-6zM16 13a1 1 0 011-1h2a1 1 0 011 1v6a1 1 0 01-1 1h-2a1 1 0 01-1-1v-6z" /></svg>,
        title: 'Vyberete produkt',
        description: 'Zvolte si z naší nabídky magnetek ten pravý produkt pro vaše vzpomínky.',
    },
    {
        icon: <svg xmlns="http://www.w3.org/2000/svg" className="h-10 w-10" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}><path strokeLinecap="round" strokeLinejoin="round" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12" /></svg>,
        title: 'Nahrajete fotografie',
        description: 'Jednoduše nahrajte své oblíbené fotografie přímo z počítače nebo mobilu.',
    },
    {
        icon: <svg xmlns="http://www.w3.org/2000/svg" className="h-10 w-10" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}><path strokeLinecap="round" strokeLinejoin="round" d="M17.657 18.657A8 8 0 016.343 7.343S7 9 9 10c0-2 .5-5 2.986-7.014A8.003 8.003 0 0112 3c2.39 0 4.5 1.1 6.014 2.986S20 9 20 11c1.002 0 2.01.203 2.986.586A8.003 8.003 0 0117.657 18.657z" /><path strokeLinecap="round" strokeLinejoin="round" d="M9.521 17.186c1.44.423 2.96.657 4.5.657 2.456 0 4.7-.93 6.387-2.474.908-.888 1.632-1.928 2.126-3.026C21.758 11.46 21.42 10.7 21 10c-1.13 0-2.234.33-3.21.918-.396.233-.82.433-1.28.61A11.002 11.002 0 0112 13c-2.445 0-4.68-.766-6.447-2.074-.523-.298-1.092-.55-1.7-.756-.423-1.44-.657-2.96-.657-4.5 0-2.456.93-4.7 2.474-6.387C6.653 4.888 7.693 4.164 8.784 3.67c.594-.27 1.22-.49 1.872-.618C10.05 3.96 9 5.38 9 7c0 1.57.53 3.03 1.42 4.142L9.52 17.186z" /></svg>,
        title: 'My se postaráme o tisk',
        description: 'Vaše fotky vytiskneme na kvalitní materiál a precizně je zpracujeme.',
    },
    {
        icon: <svg xmlns="http://www.w3.org/2000/svg" className="h-10 w-10" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}><path d="M9 17a2 2 0 11-4 0 2 2 0 014 0zM19 17a2 2 0 11-4 0 2 2 0 014 0z" /><path strokeLinecap="round" strokeLinejoin="round" d="M13 16V6a1 1 0 00-1-1H4a1 1 0 00-1 1v10a1 1 0 001 1h1m8-1a1 1 0 01-1 1H9m4-1V8a1 1 0 011-1h2.586a1 1 0 01.707.293l3.414 3.414a1 1 0 01.293.707V16a1 1 0 01-1 1h-1m-6-1a1 1 0 001 1h1M5 17a2 2 0 104 0m-4 0a2 2 0 114 0m6 0a2 2 0 104 0m-4 0a2 2 0 114 0" /></svg>,
        title: 'Doručíme až k Vám',
        description: 'Hotové magnetky vám bezpečně zabalíme a pošleme až domů.',
    }
];

export const PRODUCTS: Product[] = [
    {
      id: 'polaroid-magnets',
      name: 'Magnetky ve stylu Polaroid',
      price: 199,
      shortDescription: 'Sada 12 ks fotomagnetek v retro stylu.',
      description: 'Proměňte své digitální fotky v krásné magnetky, které vám budou každý den připomínat ty nejkrásnější okamžiky. Ideální na lednici nebo magnetickou nástěnku. <br /><br /><strong>Velikost:</strong> 7.5cm x 9cm. <br /><strong>Materiál:</strong> Kvalitní fotopapír na magnetické fólii.',
      imageUrl: 'https://i.imgur.com/wSOy2wF.jpeg',
      gallery: [],
      requiredPhotos: 12,
    },
    {
      id: 'square-magnets',
      name: 'Čtvercové magnetky',
      price: 189,
      shortDescription: 'Moderní sada 15 ks čtvercových fotomagnetek.',
      description: 'Dejte svým fotkám z Instagramu a mobilu hmotnou podobu. Čistý a minimalistický design se hodí do každého interiéru. <br /><br /><strong>Velikost:</strong> 6.5cm x 6.5cm. <br /><strong>Materiál:</strong> Kvalitní fotopapír na magnetické fólii.',
      imageUrl: 'https://i.imgur.com/NstPNg0.jpeg',
      gallery: [],
      requiredPhotos: 15,
    },
    {
      id: 'magnetic-calendar',
      name: 'Magnetický kalendář',
      price: 249,
      shortDescription: 'Vytvořte si osobní fotokalendář na celý rok.',
      description: 'Každý měsíc jiná vzpomínka! Tento magnetický kalendář je nejen praktický, ale i krásnou celoroční dekorací. Vyberte 12 fotek na každý měsíc a jednu titulní. <br/><br/><strong>Velikost:</strong> A4 na výšku nebo na šířku. <br/><strong>Materiál:</strong> Jednotlivé listy z kvalitního papíru spojené kroužkovou vazbou s magnetem na zadní straně.',
      imageUrl: 'https://i.imgur.com/gK12p3w.jpeg',
      imageUrl_portrait: 'https://i.imgur.com/gK12p3w.jpeg',
      imageUrl_landscape: 'https://i.imgur.com/83pZTYf.jpeg',
      gallery: [],
      requiredPhotos: 13, // 12 months + 1 cover
    },
];
